import streamlit as st
import os
from PIL import Image

# --- Configuration ---
st.set_page_config(layout="wide", page_title="Strava Stats Dashboard")
IMAGES_DIR = os.path.join("data", "images")

# --- Helper Function (Must be defined before use) ---
def load_image(filename):
    """Helper to load image safely."""
    path = os.path.join(IMAGES_DIR, filename)
    if os.path.exists(path):
        return Image.open(path)
    return None

# --- 1. Header & Introduction ---
st.title("🚴‍♂️ Strava Year in Review")

st.markdown("""
### About This Dashboard
This application visualizes my personal activity data from Strava. It aggregates data 
across multiple sport types (Cycling, Skiing, Swimming) and calculates a **"Mileage Equivalent"** to normalize effort across different disciplines.
""")

st.divider()

# --- 2. Activity Trends (NEW CHARTS) ---
st.header("1. Activity Trends")

col_trend1, col_trend2 = st.columns(2)

with col_trend1:
    st.subheader("Activities by Year")
    img = load_image("chart_activities_per_year.png")
    if img: st.image(img, use_container_width=True)
    else: st.info("Chart not found. Run pipeline to generate.")

with col_trend2:
    st.subheader("Cumulative Bike Miles (Last Year)")
    img = load_image("chart_cumulative_bike.png")
    if img: st.image(img, use_container_width=True)
    else: st.info("Chart not found. Run pipeline to generate.")

st.divider()

# --- 3. Global Overview ---
st.header("2. The Big Picture")
col1, col2 = st.columns([1, 2])

with col1:
    img = load_image("1_global_stats.png")
    if img: st.image(img, use_container_width=True)

with col2:
    st.markdown("""
    #### Global Statistics
    This table represents the aggregate of all data currently in the archive. 
    It highlights the total volume (distance and elevation) and the active years 
    covered by the dataset.
    """)

st.divider()

# --- 4. Sport & Gear Breakdown ---
st.header("3. Where the Effort Went")
col3, col4 = st.columns(2)

with col3:
    st.subheader("Sport Breakdown")
    img = load_image("2_sport_stats.png")
    if img: st.image(img, use_container_width=True)

with col4:
    st.subheader("Gear Usage")
    img = load_image("3_bike_stats.png")
    if img: st.image(img, use_container_width=True)

st.divider()

# --- 5. The Equity Analysis ---
st.header("4. The 'Equivalent Mile' Analysis")
col5, col6 = st.columns([2, 1])

with col5:
    img = load_image("5_equity_stats.png")
    if img: st.image(img, use_container_width=True)

with col6:
    st.markdown("""
    #### 2025 Performance
    This table shows the final "Equity" calculation. It allows for a fair comparison 
    of total aerobic output regardless of the season or sport.
    """)

st.divider()
st.caption("Generated by Strava Stats Pipeline | Built with Python & Streamlit")